### ISSUE TITLE
Remove login2.datasektionen.se and use login.datasektionen.se

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [datasektionen/login#11]
It makes no sense that we mix using `login2.datasektionen.se` and `login.datasektionen.se`. Yes, I know that the system is called `login2`. But still, only one should be used. So let's only use `login.datasektionen.se`.

The following systems need to change to use `login.datasektionen.se`:
- [ ] ~~[durn](https://github.com/datasektionen/durn/pull/1)~~
- [x] [dfunkt](https://github.com/datasektionen/dfunkt/pull/23)
- [x] [tv](https://github.com/datasektionen/Meta-TV/pull/85)
- [x] [verksamt](https://github.com/datasektionen/verksamt/pull/9)
- [x] [yoggi](https://github.com/datasektionen/yoggi/pull/3)
- [x] [knock-knock](https://github.com/datasektionen/knock-knock/pull/2)
- [x] [cashflow](https://github.com/datasektionen/cashflow/pull/97)
- [x] [calypso](https://github.com/datasektionen/calypso/pull/20)
- [x] pandora
- [x] pax
- [x] ston
- [x] zfinger
- [x] mentometer

**Comment by mathiasmagnusson** [comment]
There might still be a few repos that call it login2, but no system should use the `login2.` url anymore
